### ISSUE TITLE
[Bug] Missing creep.pull function

### ISSUE THREAD

**Issue by SavageSnowgoose** [laverdet/xxscreeps#19]
Calling '.pull' on a creep causes a type error that it is not a function.

Also note that .pull also relies on the creep being pulled to be able to call .move, even though it has no body parts, by passing the pulling creep as the move destination.

Example from the screeps docs:
creep1.move(TOP);
creep1.pull(creep2);
creep2.move(creep1);

**Comment by laverdet** [comment]
Added in c002f6a4e45e5509682efb346ea85616479bbeae
