### ISSUE TITLE
[Bug] terminal.store.getUsedCapacity(RESOURCE_ENERGY) returns wrong value

### ISSUE THREAD

**Issue by antonnyst** [laverdet/xxscreeps#20]
![screenshot](https://user-images.githubusercontent.com/35500074/128867862-f17446e7-9981-4917-af75-feb8740e33e9.png)
As seen in the image the terminal contains no energy and 70000 Z
`store.getUsedCapacity(RESOURCE_ENERGY)` incorrectly returns 70000 instead of the expected 0
This behavior was seen on the xxworld.net server

**Comment by antonnyst** [comment]
Looking at the code the issue seems to be that `OpenStore` does not handle the optional parameter resource in the methods `getCapacity` and `getUsedCapacity` as described in https://docs.screeps.com/api/#Store

**Comment by laverdet** [comment]
56e2fe395fe049be4a650b7e3acd863e735e0c54 should have fixed this, thanks!
