### ISSUE TITLE
Movement resolving algorithm differs from mmo

### ISSUE THREAD

**Issue by NesCafe62** [laverdet/xxscreeps#27]
I noticed that my creeps often get stuck in a deadlocks with my traffic amanger (which works fine on mmo). Other players spotted that too, with simple excuseMe script it created deadlocks for them.

Ways to reproduce
1.
![image](https://user-images.githubusercontent.com/1944556/129444387-6486dc4e-673b-4c9a-9e0c-c63f1127e08a.png)

if intents issued in this order
```js
creep_1.move(BOTTOM_RIGHT); // 1
creep_2.move(TOP_LEFT); // 2
creep_3.move(TOP_LEFT); // 3
creep_4.move(TOP_LEFT); // 4
```
creep1 and creep2 will swap their positions

however if to use this odrer
```js
creep_3.move(TOP_LEFT); // 3
creep_1.move(BOTTOM_RIGHT); // 1
creep_2.move(TOP_LEFT); // 2
creep_4.move(TOP_LEFT); // 4
```
or this
```js
creep_3.move(TOP_LEFT); // 3
creep_4.move(TOP_LEFT); // 4
creep_1.move(BOTTOM_RIGHT); // 1
creep_2.move(TOP_LEFT); // 2
```
or this
```js
creep_4.move(TOP_LEFT); // 4
creep_3.move(TOP_LEFT); // 3
creep_1.move(BOTTOM_RIGHT); // 1
creep_2.move(TOP_LEFT); // 2
```
no creeps are moving. while on mmo creep1 and creep2 will swap positions. (I could not test more variants becaue of that fast ticks and creeps die too fast so it was hard for me to bring them again into initial position)

2.
![image](https://user-images.githubusercontent.com/1944556/129444550-ffeb0947-7bd6-44c0-9c2f-2f0dea43fa4d.png)

If creeps 1, 2 and 3 move in triangle then 4th creep should not prevent them from moving. (and maybe this works for any contigous/closed loop). though I remember it depends on creeps speed also (terrain they are standing, their weight and count of alive move parts they have) and maybe on order of intents too (but on mmo I had no difference for various call order, if some creep can be moved by swapping or cycling in a loop they do it)

 I think this all will affect players quads (4-creep teams standing in a square/quad) too because nerby standng creep can prevent quad to swap by just moving onto their tile the same tick they are swapping.

**Comment by laverdet** [comment]
Thanks for the super helpful research on this one!
