### ISSUE TITLE
[Bug] new RoomPosition seems to not create proper RoomPosition object instance

### ISSUE THREAD

**Issue by Gadjung** [laverdet/xxscreeps#9]
expected screeps-engine behavior : 
can call .look() on proper game objects :
` stuffAtPos = Game.creeeps[creepName].pos.look()`
and dynamically created ones :  
`stuffAtPos  = new RoomPosition(x,y,roomName).look()`

error :
`error - TypeError: p.look is not a function`
`at Function.getWalkableTilesAroundRoomObject (main:13168:32)`

my bot code :
`let p = new RoomPosition(pos[i].x, pos[i].y, rObj.pos.roomName);`
`let stuffAtPos = p.look();` < error

**Comment by bastianh** [comment]
this should fix it: #11
